name: Generate tag version

on:
  workflow_dispath:
    inputs:
      description: New version
      required: true
      default: 'path'
      type: choise
      options:
        - path
        - minor
        - major

jobs:
  version:
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Generate new version
        run: npm version ${{ github.event.inputs.version }}

      - name:
        run: git push origin main --tags
